### PR TITLE
HAP-1438 - ArtifactoryGenericConfigurator class not convertible

### LINKED ISSUE #403: Plug-in v3.10.1 - Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat.
**Describe the bug**
Getting millions of these messages while starting up Jenkins with the new installed Artifactory Plug-in 3.10.1.  Jenkins takes forever to start-up because it's processing these errors.

Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat.

**To Reproduce**
Keep restarting Jenkins with the new 3.10.1 Artifactory Plug-in installed.   Downgrading to previous version stops these messages from showing up.

**Expected behavior**
No error messages while Jenkins is starting up.

**Screenshots**
Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.ArtifactoryGenericConfigurator' to use the new overridingformat. Cause: null, Could not convert the class 'org.jfrog.hudson.generic.Arti

**Versions**
- Jenkins Artifactory plugin version:  v3.10.1
- Jenkins operating system: Windows 2008 R2
- Artifactory Version: 6.10.9 rev 61009900

**Additional context**

### PR DESCRIPTION
**Pull request by yahavi**
- [x] All [tests](https://ci.appveyor.com/project/jfrog-ecosystem/jenkins-artifactory-plugin) passed. If this feature is not already covered by the tests, I added new tests.
- [x] This pull request is created in the [jfrog/jenkins-artifactory-plugin](https://github.com/jfrog/jenkins-artifactory-plugin) repository.
-----

Resolves #403

### CODE REVIEW

File: src/main/java/org/jfrog/hudson/util/converters/GenericDeployerResolverOverriderConverter.java [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+            ServerDetails deployerServerDetails = createInitialDeployDetailsFromOldDeployDetails((ServerDetails) oldDeployerDetails);
+            setServerDetailsIfNew(specsDeployerDetailsField, overrider, deployerServerDetails);
+            setServerDetailsIfNew(legacyDeployerDetailsField, overrider, deployerServerDetails);
+        } catch (ReflectiveOperationException e) {
+            converterErrors.add(getConversionErrorMessage(overrider, e));
+        }
+    }
+
+    /**
+     * Set server details if not already exist.
```
Comment (eyalbe4) [inline src/main/java/org/jfrog/hudson/util/converters/GenericDeployerResolverOverriderConverter.java:101]: Set server details if not already exist. --> Set the server details, if they don't exist already.

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
