### PR TITLE
Docker - Bugfix promotion of duplicate docker layers

### LINKED ISSUE #290: Docker fail to promote docker image with duplicate layers in manifest.json
**Describe the bug**
Docker manifest may contain duplicate layers such as `jfrog-cli-go:1.35.3` image, by promoting that image, Artifactory start to promote each layer and fail to locate the duplicate layers which exist only once.
As a result, a bad request was returned

**To Reproduce**
1. push  `jfrog-cli-go:1.35.3` image to a local repo with build-name & build-number
2. publish & promote the build info

### PR DESCRIPTION
**Pull request by Or-Gabay**
Fixes #290

### CODE REVIEW

File: src/main/java/org/jfrog/hudson/pipeline/common/docker/DockerImage.java [hunk 1]
```diff
@@ -277,7 +277,9 @@ private void setDependenciesAndArtifacts(Module buildInfoModule, String artifact
 
         List<Dependency> dependencies = new ArrayList<Dependency>();
         List<Artifact> artifacts = new ArrayList<Artifact>();
-        Iterator<String> it = DockerUtils.getLayersDigests(manifest).iterator();
+        // Filter out duplicate layers from manifest by using HashSet.
+        // Docker manifest may hold 'empty layers', as a result, docker promote will fail to promote the same layer more than once.
+        Iterator<String> it = new ArrayList<>(new HashSet<>(DockerUtils.getLayersDigests(manifest))).iterator();
         for (int i = 0; i < dependencyLayerNum; i++) {
```
Comment (eyalbe4) [inline src/main/java/org/jfrog/hudson/pipeline/common/docker/DockerImage.java:283]: Since you're now using an iterator, you should probably use it to iterate, instead of using the ```dependencyLayerNum``` value.
It should also be safer, because when using the code as is, you're relying on two different iteration methods.

Comment (Or-Gabay) [reply src/main/java/org/jfrog/hudson/pipeline/common/docker/DockerImage.java:283]: This indeed a different iterator but it iterates over dependencies. Look at line 292 which ends the dependencies flow and continues to handle artifacts.
However, looks like the scenario you are talking about could and will result in exception out of bound. I will change this to be 100% bulletproof.
