### PR TITLE
HAP-1423 - Deployed Maven Artifacts summary is missing repository in path

### LINKED ISSUE #391: DeployedMavenArtifactsAction is broken
**Describe the bug**
Since version 3.9.0 the remotePath value on each org.jfrog.hudson.pipeline.action.DeployedMavenArtifact instance is missing the repository name at the beginning of the path.
as a result the links to the deployed artifacts on the build page are broken.
this.artifactoryUrl + "/" + this.remotePath;

**To Reproduce**
Run a Maven build and deploy the artifacts

**Expected behavior**
Working links on the build page

**Versions**
- Jenkins Artifactory plugin version: 3.9.1
- Jenkins operating system: Jenkins LTS on Docker 
- Artifactory Version: 6.3.3

**Additional context**
See these extracts from the build.xml

**Latest builds with broken path:**

```    
<org.jfrog.hudson.pipeline.action.DeployedMavenArtifactsAction plugin="artifactory@3.9.0">

      <build class="flow-build" reference="../../.."/>

      <deployedMavenArtifacts class="java.util.concurrent.CopyOnWriteArrayList">

        <org.jfrog.hudson.pipeline.action.DeployedMavenArtifact>

          <artifactoryUrl>http://artifact:8081/artifactory</artifactoryUrl>

          <remotePath>com/elbitsystems/confluence/plugins/ConfluencePageLayout/1.0.23/ConfluencePageLayout-1.0.23.obr</remotePath>

          <name>ConfluencePageLayout-1.0.23.obr</name>

        </org.jfrog.hudson.pipeline.action.DeployedMavenArtifact>

        <org.jfrog.hudson.pipeline.action.DeployedMavenArtifact>

          <artifactoryUrl>http://artifact:8081/artifactory</artifactoryUrl>

          <remotePath>com/elbitsystems/confluence/plugins/ConfluencePageLayout/1.0.23/ConfluencePageLayout-1.0.23.jar</remotePath>

          <name>ConfluencePageLayout-1.0.23.jar</name>

        </org.jfrog.hudson.pipeline.action.DeployedMavenArtifact>

      </deployedMavenArtifacts>

    </org.jfrog.hudson.pipeline.action.DeployedMavenArtifactsAction>
```

**On older builds:**

``` 
    <org.jfrog.hudson.pipeline.action.DeployedMavenArtifactsAction plugin="artifactory@3.8.1">

      <build class="flow-build" reference="../../.."/>

      <deployedMavenArtifacts class="java.util.concurrent.CopyOnWriteArrayList">

        <org.jfrog.hudson.pipeline.action.DeployedMavenArtifact>

          <artifactoryUrl>http://artifact:8081/artifactory</artifactoryUrl>

          <remotePath>local-lib-Corporate_Dev/com/elbitsystems/confluence/plugins/ConfluencePageLayout/1.0.21/ConfluencePageLayout-1.0.21.jar</remotePath>

          <name>ConfluencePageLayout-1.0.21.jar</name>

        </org.jfrog.hudson.pipeline.action.DeployedMavenArtifact>

        <org.jfrog.hudson.pipeline.action.DeployedMavenArtifact>

          <artifactoryUrl>http://artifact:8081/artifactory</artifactoryUrl>

          <remotePath>local-lib-Corporate_Dev/com/elbitsystems/confluence/plugins/ConfluencePageLayout/1.0.21/ConfluencePageLayout-1.0.21.obr</remotePath>

          <name>ConfluencePageLayout-1.0.21.obr</name>

        </org.jfrog.hudson.pipeline.action.DeployedMavenArtifact>

      </deployedMavenArtifacts>

    </org.jfrog.hudson.pipeline.action.DeployedMavenArtifactsAction>
```

### PR DESCRIPTION
**Pull request by RobiNino**
Due to the removal of the repository from the remote path of artifacts in [jfrog/build-info#398](https://github.com/jfrog/build-info/pull/398), the repository was missing in the path of the artifacts in the summary.
Fixes #391.

### CODE REVIEW

File: src/main/java/org/jfrog/hudson/pipeline/common/types/deployers/MavenDeployer.java [hunk 1]
```diff
@@ -121,32 +120,34 @@ private static MavenDeployer createEmptyDeployer() {
...
      * Adds artifacts from the provided DeployDetails map to the Deployed Maven Artifacts Summary Action.
      */
     public static void addDeployedArtifactsActionFromDetails(Run build, String artifactoryUrl, Map<String, Set<DeployDetails>> deployableArtifactsByModule) {
         deployableArtifactsByModule.forEach((module, detailsSet) -> {
+            // Add only if whole module contains maven artifacts.
             boolean isMaven = true;
-            List<Artifact> curArtifacts = Lists.newArrayList();
+            List<DeployedMavenArtifact> curArtifacts = Lists.newArrayList();
             for (DeployDetails curDetails : detailsSet) {
                 isMaven = (curDetails.getPackageType() == DeployDetails.PackageType.MAVEN) && isMaven;
```
Comment (eyalbe4) [inline src/main/java/org/jfrog/hudson/pipeline/common/types/deployers/MavenDeployer.java:145]: Wouldn't it be better to just return here, if the package type is not maven?
This will also make the ```if (isMaven) {``` at the bottom of the method redundant.

**Review by eyalbe4 — CHANGES_REQUESTED** [review]
